spring.application.name=proyecto

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bd_aerolinea?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Propiedades JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Puerto del Servidor Backend
server.port=8080

# Ruta Swagger UI (Documentacion de la API)
springdoc.swagger-ui.path=/swagger-ui.html